### ISSUE TITLE
Kicks you out

### ISSUE THREAD

**Issue by DarthLikoney** [TheMisterFish/Fabric_TwinSession#10]
**Describe the bug**
When you play in 1.21.3 it doesnt work. I tried in a singleplayer world, when I joined with the second Instance it closed the first that launched the world. With a Server it kicks the Instance on the server out, with the message "logged in from another location"

**Versions (please complete the following information):**
- Minecraft: [1.21.3]
- Fabric API: [0.107.3+1.21.3]
- Mod Version: [1.0.3]

**Comment by TheMisterFish** [comment]
There's a simple explanation for that:
![image](https://github.com/user-attachments/assets/5a9ad15c-a2c6-4fd4-80d7-0743158c1787)

**Comment by TheMisterFish** [comment]
1.1.0 is released for mc 1.21.3
