### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rendable** [TheMisterFish/Fabric_TwinSession#15]
**Describe the bug**
When trying to use TwinSession on the server "play.minebox.co" I receive the message "Couldn't pre connect user" which I wasn't able to find anything online about. Occasionally if I click reconnect, I will instead get the message "You are already connected to this proxy"
 
**To Reproduce**
1. Go to 'Multiplayer' with the TwinSession mod enabled, while already connected to the server on the same account.
2. Click on 'play.minebox.co'
3. See error

**Expected behavior**
The second session will connect to the server with the name modified as per the mod description.

**Screenshots**
![image](https://github.com/user-attachments/assets/7fa581b6-8d14-45f0-84b9-8a3898864dae)
![image](https://github.com/user-attachments/assets/705294b6-6c36-4937-815a-063888852ac8)

**Versions**
- Minecraft: 1.21.3
- Fabric Loader: 0.110.0
- Mod Version: 1.1.0

**Additional context**
If this is something that is due to how the server is set up and can't be worked around, I totally understand! Thanks! :)

**Comment by TheMisterFish** [comment]
If I understand correct you've installed the mod locally. This way you can open up a singleplayer world, open it up to lan, and connect with a second cliënt.

The mod is either a client mod, or server mod. If you want to use the mod on a server the admin has to install the mod on the server. 

If the mod is installed on the server, it is not required to have it installed locally to work.
